apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: lorenzofavaro/bibliotechk8:auth-service
          env:
           - name: SPRING_DATASOURCE_PASSWORD
             value: admin
           - name: SPRING_DATASOURCE_URL
             value: jdbc:postgresql://dbpostgresql:5432/users
           - name: SPRING_DATASOURCE_USERNAME
             value: postgres
           - name: SPRING_PROFILES_ACTIVE
             value: docker
           - name: eureka.client.serviceUrl.defaultZone
             value: http://eureka-server:8761/eureka/
          ports:
            - containerPort: 9100
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 9100
  type: LoadBalancer