apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  labels:
    app: eureka-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: lorenzofavaro/bibliotechk8:eureka-server
          ports:
            - containerPort: 8762
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: default
spec:
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 8762
  type: NodePort