version: '3'

services:
  dbpostgresql:
    image: "postgres"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      restart: unless-stopped
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "9300:9300"
    depends_on:
      - dbpostgresql
